name: Build

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'docs/**'
      - README.md

jobs:
  renderer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
    - uses: pnpm/action-setup@v4
    - run: pnpm install --frozen-lockfile
    - run: pnpm make-index-files
    - run: pnpm lint
    - run: pnpm test
    - run: pnpm build
    - run: pnpm audit --prod --audit-level high
    - uses: actions/upload-artifact@v7
      with:
        name: renderer-dist
        path: ./renderer/dist
        retention-days: 1

  package:
    needs: renderer
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
    - uses: pnpm/action-setup@v4
    - uses: actions/download-artifact@v8
      with:
        name: renderer-dist
        path: ./renderer/dist
    - run: pnpm install --frozen-lockfile
    - run: pnpm --dir main build
    - run: pnpm --dir main package -- -p onTagOrDraft
      working-directory: ./main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Hash
      if: ${{ startsWith(matrix.os, 'windows') }}
      run: type .\main\dist\latest.yml
    - name: Hash
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: cat ./main/dist/latest-linux.yml
    - name: Hash
      if: ${{ startsWith(matrix.os, 'macos') }}
      run: cat ./main/dist/latest-mac.yml
